// Generated by CoffeeScript 1.6.3
(function() {
  var Backbone, Router, Routes, Server, r, server;

  Backbone = require('backbone');

  Router = require('./routes/routes.js');

  Routes = (function() {
    function Routes() {
      this.routes = new Backbone.Collection();
    }

    return Routes;

  })();

  r = new Routes();

  Server = (function() {
    Server.prototype.express = require('express');

    Server.prototype.http = require('http');

    Server.prototype.path = require('path');

    Server.prototype.app = null;

    Server.prototype.routes = null;

    function Server() {
      this.app = this.express();
      this.setUpExpress();
      this.setUpRoutes();
      this.createServer();
    }

    Server.prototype.setUpExpress = function() {
      this.app.set('port', process.env.PORT || 3000);
      this.app.set('views', this.path.join(__dirname, 'views'));
      this.app.set('view engine', 'jade');
      this.app.use(this.express.favicon());
      this.app.use(this.express.logger('dev'));
      this.app.use(this.express.json());
      this.app.use(this.express.urlencoded());
      this.app.use(this.express.methodOverride());
      this.app.use(this.app.router);
      return this.app.use(this.express["static"](this.path.join(__dirname, 'public')));
    };

    Server.prototype.setUpRoutes = function() {
      this.app.get('/', Router.index);
      this.app.get('/users', Router.list);
      this.app.get('/demos/:type', Router.demos);
      this.app.get('/maps/:renderer', Router.map);
      this.app.get('/codem', Router.codem);
      this.app.get('/loaders', Router.loaders);
      this.app.get('/tgsData', Router.thinkData);
      this.app.get('/tgs', Router.tgs);
      if ('development' === this.app.get('env')) {
        return this.app.use(this.express.errorHandler());
      }
    };

    Server.prototype.createServer = function() {
      var _this = this;
      return this.http.createServer(this.app).listen(this.app.get('port'), function() {
        return console.log('Express server listening on port' + _this.app.get('port'));
      });
    };

    return Server;

  })();

  server = server || new Server();

}).call(this);
