// Generated by CoffeeScript 1.6.3
(function() {
  var Backbone, Routes, Server, codem, demos, loaders, maps, r, routes, server, user;

  Backbone = require('backbone');

  routes = require('./routes');

  user = require('./routes/user');

  demos = require('./routes/demos');

  maps = require('./routes/maps');

  codem = require('./routes/codem');

  loaders = require('./routes/loaders');

  Routes = (function() {
    function Routes() {
      this.routes = new Backbone.Collection();
    }

    return Routes;

  })();

  r = new Routes();

  Server = (function() {
    Server.prototype.express = require('express');

    Server.prototype.http = require('http');

    Server.prototype.path = require('path');

    Server.prototype.app = null;

    Server.prototype.routes = null;

    function Server() {
      this.app = this.express();
      this.setUpExpress();
      this.setUpRoutes();
      this.createServer();
    }

    Server.prototype.setUpExpress = function() {
      this.app.set('port', process.env.PORT || 3000);
      this.app.set('views', this.path.join(__dirname, 'views'));
      this.app.set('view engine', 'jade');
      this.app.use(this.express.favicon());
      this.app.use(this.express.logger('dev'));
      this.app.use(this.express.json());
      this.app.use(this.express.urlencoded());
      this.app.use(this.express.methodOverride());
      this.app.use(this.app.router);
      return this.app.use(this.express["static"](this.path.join(__dirname, 'public')));
    };

    Server.prototype.setUpRoutes = function() {
      this.app.get('/', routes.index);
      this.app.get('/users', user.list);
      this.app.get('/demos/:type', demos.demos);
      this.app.get('/maps/:renderer', maps.index);
      this.app.get('/codem', codem.codem);
      this.app.get('/loaders', loaders.loaders);
      if ('development' === this.app.get('env')) {
        return this.app.use(this.express.errorHandler());
      }
    };

    Server.prototype.createServer = function() {
      var _this = this;
      return this.http.createServer(this.app).listen(this.app.get('port'), function() {
        return console.log('Express server listening on port' + _this.app.get('port'));
      });
    };

    return Server;

  })();

  server = server || new Server();

}).call(this);
